### ISSUE TITLE
Youbike's data source changed.

### ISSUE THREAD

**Issue by matlinuxer2** [le-moulin-studio/bike-friend#4]
Just found youbike data reset to 0 , which caused by taipei's youbike open data change.

https://www.facebook.com/app.bikeFriend/posts/1072995242712823

Just tested the data source below, to make sure upstream data updates properly.
![2015-11-05_172708_1212x509_scrot](https://cloud.githubusercontent.com/assets/53925/10964999/157249ca-83e5-11e5-9f14-45f733827c8e.png)

and got pretty print sceenshot of data source's format.

![2015-11-05_173841_1280x800_scrot](https://cloud.githubusercontent.com/assets/53925/10965002/19d3c368-83e5-11e5-9ede-aad94a6cbaff.png)

**Comment by matlinuxer2** [comment]
Just found "YouBikeStationParser" in the file:
server/src/main/java/com/lemoulinstudio/bikefriend/webapp/ubike/YouBikeStationParser.java
Is this the correct place to fix it? 

If I want to help, what can do I do to help this? thanks~

**Comment by green-coder** [comment]
Hi mat, sorry for the delay, I just notice now that you filed this issue.

Yes, I need some help. Right now, http://data.taipei/ is unreachable so I don't know if they resolved the problem or not.

Pull requests are welcome.

**Comment by green-coder** [comment]
I am working on a fix. At the moment I cannot test because data source give this error: 系統維護中，請稍後再試一次

**Comment by matlinuxer2** [comment]
Thank you first for your effort!

I just try your URL and other URLs, I found all incorrect URLs will lead to same error message: "系統維護中，請稍後再試一次"

The correct URL should be "http://data.taipei/youbike" 
According to the intro page ( http://data.taipei/opendata/datalist/datasetMeta?oid=8ef1626a-892a-4218-8344-f7ac46e1aa48 ), and my real test.
The URL will redirect to another URL, which download a gziped json data.
So the program should be able to follow the redirection and uncompressed the data it refered.

The following command can get the result on Linux.
```
wget -O - --quiet http://data.taipei/youbike  | gzip -d
```

I haven't handled this problem with java, any idea?

**Comment by green-coder** [comment]
Hi Mat !

I made a new release, it should be available on the Google's PlayStore soon.

I found the solution for the redirection [there](http://stackoverflow.com/questions/12870385/301-302-redirect-not-working-in-android-work-differently-in-different-versions)

Thank you for your precious help !
